name: Trainer
epochs: 200
validate_on_training_data: true #Validate on the traing set in addition to on the validation set
print_metrics: false #Print results after each epoch
use_amp: true #Use mixed precision
threshold_tuning: false #Picks the optimal threshold based on the validation set
clip_grad_norm: 1 #Clip gradient norm to this value
clip_value: 10 #Clip the value of the gradients to this value
