name: PLM-ICD Hyperparameter Sweep | MDACE ICD9 Code | adversarial training
program: train_plm.py
method: grid
early_terminate:
    type: hyperband
    min_iter: 5
    eta: 0.8
metric:
  name: validation.f1_micro_tuned
  goal: maximize
parameters:
  experiment:
    value: mdace_icd9_code/plm_icd
  optimizer:
    value: adamw
  lr_scheduler:
    value: warmup_linear_decay
  loss:
    value: advesarial_training_loss
  trainer.epochs:
    value: 20
  trainer.threshold_tuning:
    value: true
  trainer.validate_on_training_data:
    value: false
  data.max_length:
    value: 6000
  dataloader.max_batch_size:
    value: 2
  optimizer.configs.lr:
    values: [1e-5, 3e-5]
  optimizer.configs.weight_decay:
    value: 0
  loss.configs.lambda_1:
    value: 1e-2
  loss.configs.lambda_2:
    value: 0.5
  loss.configs.epsilon:
    value: 1e-5
  loss.configs.attack_type:
    value: pgd







command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
