name: PLM-ICD Hyperparameter Sweep | MDACE ICD9 Code | Double Backpropagation
program: train_plm.py
method: random
early_terminate:
    type: hyperband
    min_iter: 5
    eta: 1.5
metric:
  name: validation.f1_micro_tuned
  goal: maximize
parameters:
  experiment:
    value: mdace_icd9_code/plm_icd_cross_attention
  optimizer:
    value: adamw
  model.configs.loss:
    value: double_backpropagation_loss
  lr_scheduler:
    value: warmup_linear_decay
  trainer.epochs:
    value: 20
  trainer.threshold_tuning:
    value: true
  trainer.validate_on_training_data:
    value: false
  data.max_length:
    value: 6000
  dataloader.max_batch_size:
    value: 4
  callbacks:
    value: sweep
  optimizer.configs.lr:
    values: [3e-5, 5e-5]
  optimizer.configs.weight_decay:
    values: [0, 1e-5]
  model.configs.lambda_1:
    values: [1e-2, 1e-3, 1e-4, 1e-5, 1e-6]





command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
