name: PLM-ICD Hyperparameter Sweep | MDACE ICD9 Code | Supervised Attention
program: train_plm.py
method: random
early_terminate:
    type: hyperband
    min_iter: 5
    eta: 1.5
metric:
  name: validation.f1_micro_tuned
  goal: maximize
parameters:
  experiment:
    value: mdace_icd9_code/plm_icd_cross_attention
  optimizer:
    value: adamw
  lr_scheduler:
    value: warmup_linear_decay
  model.configs.loss:
    value: kl_attention_loss
  trainer.epochs:
    value: 20
  trainer.threshold_tuning:
    value: true
  trainer.validate_on_training_data:
    value: false

  data.max_length:
    value: 6000
  callbacks:
    value: sweep
  optimizer.configs.lr:
    values: [3e-5, 5e-5]
  optimizer.configs.weight_decay:
    value: 0
  model.configs.lambda_1:
    values: [2.5, 2 , 1, 0.5,0.1,0.01]





command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
