program: train_plm.py
name: MDACE ICD-9 | multi seeds experiments
method: grid
metric:
  name: validation.f1_micro_tuned
  goal: maximize
parameters:
  experiment:
    values:
      - mdace_icd9_code/plm_icd
      - mdace_icd9_code/plm_icd_igr
      - mdace_icd9_code/plm_icd_supervised
      - mdace_icd9_code/plm_icd_pgd
  seed:
    values: [0,1,2,3,4,5,6,7,8,9]


command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
